#define ENABLE_AUTH 1
#define QUERY_PARAMS 2
#define BODY_PARAMS 3
#define COMMENT 4
#define GET 5
#define POST 6
#define DELETE 7
#define PUT 8
#define PATCH 9
#define EXPRESS_VAR 10
#define SYNTAX_ERROR 11
#define DOCUMENTATION 12
#define RETURN 13
#define IS_ARRAY 14
#define IS_OBJECT 15
#define AUTH_DISABLE 16
#define AUTH_ENABLE 17
#define PATH 18
#define VARNAME 19
#define STRING 20
#define FLUTTER_PATH 21
#define ANGULAR_PATH 22
#define SERVER_PORT 23
#define ROUTER_NAME 24
#define MIDDLE_NAME 25
#define ENABLE_UPLOAD 26
#define ANDROID_PATH 27
#define UPLOAD 28
#define VAR_AND_TYPE 29
#define OBJECT_NAME 30
#define NUMBER 31